USE master;
GO

CREATE DATABASE APIDemo;
GO

USE APIDemo;

CREATE TABLE Product(
	product_ID INT PRIMARY KEY IDENTITY,
	productName NVARCHAR(50) NOT NULL DEFAULT ' ',
	serving NVARCHAR(30) NOT NULL DEFAULT ' ',
	package NVARCHAR(30) NOT NULL DEFAULT ' ',
	prices NVARCHAR(30) NOT NULL DEFAULT ' ',
	qty NVARCHAR(30) NOT NULL DEFAULT ' ',
	)
GO